version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 loss_cafe.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: losscafe_db
      DATABASE_USER: losscafe_user
      DATABASE_PASSWORD: losscafe_pass
      DATABASE_HOST: db  # Corrected to 'db'
      DATABASE_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: losscafe_db
      POSTGRES_USER: losscafe_user
      POSTGRES_PASSWORD: losscafe_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
