# Generated by Django 5.1.1 on 2024-10-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
