# Generated by Django 5.1.1 on 2024-10-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_category_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name2',
        ),
    ]
