# Generated by Django 5.1.1 on 2024-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_category_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubackground',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_icon_images/'),
        ),
    ]
