# Generated by Django 5.1.1 on 2024-10-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_menubackground_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('icon_instagram', models.ImageField(upload_to='icons_images/')),
                ('icon_facebook', models.ImageField(upload_to='icons_images/')),
                ('icon_twitter', models.ImageField(upload_to='icons_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
