# Generated by Django 5.1.1 on 2024-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_footerdescription_footerlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterDescription',
        ),
        migrations.DeleteModel(
            name='FooterLocation',
        ),
        migrations.AddField(
            model_name='menubackground',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menubackground',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='icon_facebook',
            field=models.ImageField(default='', upload_to='icons_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menubackground',
            name='icon_instagram',
            field=models.ImageField(default='', upload_to='icons_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menubackground',
            name='icon_twitter',
            field=models.ImageField(default='', upload_to='icons_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menubackground',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='telephone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
