# Generated by Django 5.1.1 on 2024-10-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_delete_footerdescription_delete_footerlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubackground',
            name='href_facebook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='href_instagram',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='href_twitter',
            field=models.CharField(default='', max_length=200),
        ),
    ]
