# Generated by Django 5.1.1 on 2024-10-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_menubackground_href_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menubackground',
            name='icon_facebook',
        ),
        migrations.RemoveField(
            model_name='menubackground',
            name='icon_instagram',
        ),
        migrations.RemoveField(
            model_name='menubackground',
            name='icon_twitter',
        ),
    ]
