# Generated by Django 4.2.16 on 2024-10-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_remove_menubackground_icon_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subsubcategory_images/'),
        ),
        migrations.CreateModel(
            name='SubSubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subsubsubcategory_images/')),
                ('price', models.CharField(max_length=100)),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubsubcategories', to='cafe.subsubcategory')),
            ],
        ),
    ]
