# Generated by Django 4.2.16 on 2024-10-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_subsubcategory_price_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
