# Generated by Django 4.2.16 on 2026-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subsubsubcategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
