# Generated by Django 4.2.16 on 2026-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubackground',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube veya Vimeo video linki (mekan tanıtımı)', max_length=500),
        ),
    ]
