# Generated by Django 4.2.16 on 2026-03-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_add_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Kısa başlık (örn. 'MENÜ KAMPANYASI' veya 'Günün Fırsatı').", max_length=150)),
                ('title_en', models.CharField(blank=True, default='', help_text='İngilizce başlık (boş bırakılırsa Türkçe başlık kullanılır).', max_length=150)),
                ('description', models.TextField(help_text="Detay yazısı (örn. 'Hamburger + Kola + Patates sadece 100 TL').")),
                ('description_en', models.TextField(blank=True, default='', help_text='İngilizce açıklama (boş bırakılırsa Türkçe açıklama kullanılır).')),
                ('price_text', models.CharField(blank=True, default='', help_text="İsteğe bağlı fiyat metni (örn. '100 TL').", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Kampanya görseli (örn. hamburger menü fotoğrafı).', null=True, upload_to='campaign_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Sadece aktif olan kampanya ana sayfada popup olarak gösterilir.')),
                ('show_on_home', models.BooleanField(default=True, help_text='İşaretliyse kategori (ana menü) sayfasında gösterilir.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='address_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='menubackground',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='subsubsubcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menubackground',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube, Vimeo veya Instagram Reel linki (mekan tanıtımı)', max_length=500),
        ),
    ]
