# Generated by Django 4.2.16 on 2026-03-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_campaign_category_description_en_category_name_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menubackground',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='menubackground',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='menubackground',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subsubsubcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subsubsubcategory',
            name='name_en',
        ),
    ]
